version: '3'

services:
  rabbit:
    image: rabbitmq:3.7-management
    hostname: rabbit
    container_name: "rabbitmq_3_7"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia
      - ./log:/var/log/rabbitmq   # 日志为空